services:
  - type: web
    name: sneakout-server
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: sneakout-db
          property: connectionString
      - key: Jwt_Secret
        generateValue: true
      - key: PORT
        value: 10000

